name: Build and deploy ASP.Net Core app to Azure Web App - nuget-dependencies

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore ./NugetDependencyChecker.WebApi/NugetDependencyChecker.WebApi.csproj

      - name: Build with dotnet
        run: dotnet build ./NugetDependencyChecker.WebApi/NugetDependencyChecker.WebApi.csproj --configuration Release

      - name: Publish the application
        run: dotnet publish ./NugetDependencyChecker.WebApi/NugetDependencyChecker.WebApi.csproj -c Release -o ./published-app

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./published-app

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_043A5C8A72054E358E85CA8324BBDAB6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7206E7BFE8724DB7B144B887B332C357 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_80891A99381747D0A96AF6E43C9B559A }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'nuget-dependencies'
          slot-name: 'Production'
          package: ./published-app
